export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_DISHES = 'ADD_DISHES';
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const PROMOS_FAILED = 'PROMOS_FAILED';

export const ADD_LEADERS = 'ADD_LEADERS';
export const LEADERS_LOADING = 'LEADERS_LOADING';
export const LEADERS_FAILED = 'LEADERS_FAILED';

export const ADD_FEEDBACK = 'ADD_FEEDBACK';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_ERR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_ERR = 'FAVORITES_ERR';
export const ADD_FAVORITE = 'ADD_FAVORITE';
